/**
 * Czech payroll ruleset — tax year 2026.
 *
 * Every value here was verified against a primary source on 2026-08-24 and
 * carries the id of that source in data/calculators/cz-employer-cost/2026/
 * sources.ts. Nothing is inherited from a previous year and nothing is inferred
 * from a payroll blog.
 *
 * WHERE THIS RULESET DELIBERATELY REFUSES TO ANSWER
 * ─────────────────────────────────────────────────
 * Three things could not be established from a primary source, and are carried
 * as assumptions or exclusions rather than guessed at:
 *
 *   • how the health premium's thirds are rounded when the premium is not
 *     divisible by three — only "the shares sum to the premium" is law;
 *   • the pro-rata formula for a partial-month health minimum — § 3 odst. 9
 *     states the principle and no authority publishes the divisor or rounding;
 *   • whether the annual social maximum is disapplied to the employer-liability
 *     premium as a matter of law — both administrators say it is, no statute
 *     does, and a literal reading of the decree would arguably cap it.
 *
 * Each is surfaced to the user as an assumption at the point it bites.
 *
 * A NOTE FOR CZ/2027
 * ──────────────────
 * Do not edit this file when 2027 arrives. Add jurisdictions/cz/2027.ts. The
 * government decrees that move the average wage, the minimum wage, the 23 %
 * threshold and the maximum assessment base are published each autumn, which is
 * what `reviewDueFrom` points at.
 */

import type { CzRuleset } from './ruleset';

const S = {
  minimumWage: 'mpsv-minimalni-mzda-2026',
  coefficient: 'nv-285-2024-koeficient',
  mfPrediction: 'mf-sdeleni-312-2025',
  socialRates: 'cssz-sazby-2026',
  socialOverview: 'cssz-prehled-2026',
  socialMax: 'cssz-max-vz-2026',
  socialAct: 'zakon-589-1992',
  employerDiscount: 'cssz-sleva-zamestnavatele',
  pensioner: 'cssz-pracujici-duchodci',
  healthAct: 'zakon-592-1992',
  healthSplitAct: 'zakon-48-1997',
  vzp: 'vzp-metodika-vymerovaci-zaklad',
  healthAmendment: 'zakon-289-2025',
  taxAct: 'zakon-586-1992',
  fs: 'fs-zalohy-zavisla-cinnost',
  credits: 'portal-slevy-2026',
  liabilityDecree: 'vyhlaska-125-1993',
  koop: 'koop-zakonne-pojisteni',
} as const;

export const CZ_2026: CzRuleset = {
  jurisdiction: 'CZ',
  taxYear: 2026,
  effectiveFrom: '2026-01-01',
  effectiveTo: '2026-12-31',
  // The decrees that fix next year's parameters appear from October. That is
  // when this ruleset becomes re-checkable, not a fixed number of days after it
  // was written.
  reviewDueFrom: '2026-10-01',

  // ── Social insurance ─────────────────────────────────────────────────────
  employeeSocialRate: {
    value: 7.1,
    sourceId: S.socialRates,
    legalBasis: '§ 7 odst. 1 písm. d) zákona č. 589/1992 Sb.',
    status: 'confirmed-official',
    note: '6,5 % důchodové + 0,6 % nemocenské. Pojistné se zaokrouhluje nahoru na celé koruny až po výpočtu v plné přesnosti.',
  },
  employerSocialRates: [
    {
      class: 'standard',
      rate: {
        value: 24.8,
        sourceId: S.socialRates,
        legalBasis: '§ 7 odst. 1 písm. a) zákona č. 589/1992 Sb.',
        status: 'confirmed-official',
        note: '21,5 % důchodové + 2,1 % nemocenské + 1,2 % státní politika zaměstnanosti.',
      },
      appliesToCs: 'Zaměstnanci, kteří nevykonávají žádnou ze zvláštních činností podle § 5a odst. 1.',
    },
    {
      class: 'rescue_services',
      rate: {
        value: 29.8,
        sourceId: S.socialRates,
        legalBasis: '§ 7 odst. 1 písm. b) zákona č. 589/1992 Sb.',
        status: 'confirmed-official',
        note: 'Pouze zdravotnický záchranář a člen jednotky HZS podniku. Neaplikuje se na běžné zaměstnance.',
      },
      appliesToCs: 'Zdravotničtí záchranáři a členové jednotky hasičského záchranného sboru podniku.',
    },
    {
      class: 'risk_work',
      rate: {
        value: 27.8,
        sourceId: S.socialRates,
        legalBasis: '§ 7 odst. 1 písm. c) zákona č. 589/1992 Sb.',
        status: 'confirmed-official',
        note: 'Riziková zaměstnání: 27,8 % pro rok 2026, 28,8 % pro 2027, 29,8 % od 2028. Sazba je ročníkově odstupňovaná — nelze ji přenášet mezi roky.',
      },
      appliesToCs: 'Zaměstnanci vykonávající rizikové zaměstnání.',
    },
  ],
  maxAnnualSocialBase: {
    value: 2_350_416,
    sourceId: S.socialMax,
    legalBasis: '§ 15a zákona č. 589/1992 Sb.',
    status: 'confirmed-official',
    note: '48 × průměrná mzda 48 967 Kč. Roční kumulativní strop. U jediného zaměstnavatele nad strop neodvádí ani zaměstnanec, ani zaměstnavatel (§ 15a odst. 4).',
  },
  participationThresholdMonthly: {
    value: 4_500,
    sourceId: S.socialOverview,
    legalBasis: '§ 6 odst. 2 zákona č. 187/2006 Sb.',
    status: 'confirmed-official',
    note: 'Rozhodný příjem pro účast na nemocenském pojištění. Pod touto částkou se sociální pojistné neodvádí vůbec — ani zaměstnanec, ani zaměstnavatel. Odvozeno jako 10 % průměrné mzdy zaokrouhlených dolů na celých 500 Kč.',
  },
  employerDiscount: {
    status: 'confirmed-official',
    sourceId: S.employerDiscount,
    legalBasis: '§ 7a–§ 7c zákona č. 589/1992 Sb.',
    ratePercent: {
      value: 5,
      sourceId: S.employerDiscount,
      legalBasis: '§ 7b odst. 1 zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: '5 % z úhrnu vyměřovacích základů zaměstnanců, na které se sleva uplatňuje; zaokrouhluje se nahoru jednou z úhrnu, nikoli po zaměstnancích.',
    },
    weeklyHoursMin: {
      value: 8,
      sourceId: S.employerDiscount,
      legalBasis: '§ 7a odst. 2 zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: 'Rozsah SJEDNANÉ pracovní doby, nikoli skutečně odpracovaných hodin. Pásmo je absolutní, nikoli relativní k úvazku zaměstnavatele.',
    },
    weeklyHoursMax: {
      value: 30,
      sourceId: S.employerDiscount,
      legalBasis: '§ 7a odst. 2 zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: 'Sjednaná doba musí být zároveň kratší než stanovená týdenní pracovní doba u daného zaměstnavatele.',
    },
    monthlyBaseCeilingMultiple: {
      value: 1.5,
      sourceId: S.employerDiscount,
      legalBasis: '§ 7a odst. 3 písm. a) zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: '1,5 × 48 967 = 73 450,5 → nahoru = 73 451 Kč pro rok 2026. Přesně 73 451 Kč ještě nárok nevylučuje („vyšší než"). Nekrátí se za neúplný měsíc.',
    },
    hourlyBaseCeilingPercent: {
      value: 1.15,
      sourceId: S.employerDiscount,
      legalBasis: '§ 7a odst. 3 písm. b) zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: '1,15 % z 48 967 = 563,12 → nahoru = 564 Kč/hod pro rok 2026. Podíl i hranice se před porovnáním zaokrouhlují nahoru na celé koruny.',
    },
    categoriesExemptFromHoursCondition: ['under_21'],
    unverifiableConditionsCs: [
      'Péče o dítě do 10 let a rodičovský či pěstounský vztah k němu.',
      'Péče o osobu blízkou a stupeň její závislosti.',
      'Studium a jeho kvalifikovaná forma.',
      'Datum zahájení rekvalifikace.',
      'Invalidita zaměstnance.',
      'Zda oznámení záměru bylo ČSSZ doručeno včas a stále trvá — a zda si slevu na téhož zaměstnance nezaregistroval dříve jiný zaměstnavatel.',
      'Zda je zaměstnavatel zaměstnavatelem na chráněném trhu práce.',
      'Zda je zaměstnanec uveden ve výkazu nákladů podle § 120e odst. 5 zákona o zaměstnanosti.',
      'Právní kvalifikace jednotlivých hodin nepřítomnosti — testy podle písm. b) a c) počítají jiné hodiny.',
    ],
    note: 'Znění § 7a–§ 7c je pro rok 2026 nezměněno; ověřeno porovnáním konsolidovaných znění účinných 1. 1. 2026, 1. 7. 2026 a 1. 1. 2027 — shodná do znaku.',
  },
  workingPensioner: {
    status: 'confirmed-official',
    sourceId: S.pensioner,
    legalBasis: '§ 7d, § 7e zákona č. 589/1992 Sb.',
    employeeSocialRate: {
      value: 6.5,
      sourceId: S.pensioner,
      legalBasis: '§ 7e odst. 1 zákona č. 589/1992 Sb.',
      status: 'confirmed-official',
      note: 'Toto je SAZBA SLEVY, nikoli snížená sazba pojistného. Nejprve se stanoví pojistné 7,1 % (nahoru), poté sleva 6,5 % (nahoru, samostatně), a teprve rozdíl se srazí. Sazba „0,6 %" neexistuje v žádném ustanovení a nesmí se používat.',
    },
    employerRateChanges: {
      value: false,
      sourceId: S.pensioner,
      legalBasis: '§ 7 odst. 1 zákona č. 589/1992 Sb.',
      // Downgraded from confirmed to derived after the adversarial review: no
      // primary source says in words "sazba zaměstnavatele se nemění". The
      // conclusion rests on § 7 containing no pensioner variant, on §§ 7d–7e
      // conferring the right on the EMPLOYEE, and on ČSSZ describing the result
      // as what the employer "zaměstnanci srazí". Strong, but inferred.
      status: 'derived-from-official',
      note: 'Sazba zaměstnavatele se u pracujícího starobního důchodce nemění. Žádný pramen to neuvádí výslovně — plyne to z toho, že § 7 žádnou variantu pro důchodce neobsahuje a sleva podle §§ 7d–7e náleží zaměstnanci.',
    },
    note: 'Účinnost od 1. 1. 2025 (nikoli od 1. 7. 2024). Sleva se uplatňuje na základě nároku uplatněného zaměstnancem. Souběh více zaměstnání u téhož zaměstnavatele není primárními prameny vyřešen a není modelován.',
  },

  // ── Health insurance ─────────────────────────────────────────────────────
  employeeHealthRate: {
    value: 4.5,
    sourceId: S.healthSplitAct,
    legalBasis: '§ 9 odst. 2 zákona č. 48/1997 Sb.',
    status: 'derived-from-official',
    note: 'POZOR: 4,5 % není zákonná sazba. Zákon zná jedinou sazbu 13,5 %; zaměstnanec hradí JEDNU TŘETINU vypočteného a zaokrouhleného pojistného. Hodnota je zde vedena pouze pro popis v uživatelském rozhraní a engine z ní nepočítá.',
  },
  employerHealthRate: {
    value: 9,
    sourceId: S.healthSplitAct,
    legalBasis: '§ 9 odst. 2 zákona č. 48/1997 Sb.',
    status: 'derived-from-official',
    note: 'Rovněž není zákonná sazba — jde o dvě třetiny pojistného. Engine z této hodnoty nepočítá.',
  },
  healthTotalRate: {
    value: 13.5,
    sourceId: S.healthAct,
    legalBasis: '§ 2 odst. 1 zákona č. 592/1992 Sb.',
    status: 'confirmed-official',
    note: 'Jediná zákonná sazba. „Výše pojistného činí 13,5 % z vyměřovacího základu za rozhodné období." Zaokrouhluje se nahoru na celé koruny JEDNOU (§ 2 odst. 2), teprve poté se dělí na třetiny.',
  },
  healthMinimum: {
    status: 'confirmed-official',
    sourceId: S.healthAct,
    legalBasis: '§ 3 odst. 4, 6, 8, 9, 10 zákona č. 592/1992 Sb.',
    monthlyMinimum: {
      value: 22_400,
      sourceId: S.vzp,
      legalBasis: '§ 3 odst. 6 zákona č. 592/1992 Sb.',
      status: 'confirmed-official',
      note: 'Minimálním vyměřovacím základem je minimální mzda. NEKRÁTÍ se podle délky úvazku — VZP výslovně „bez ohledu na délku pracovního úvazku". Minimální pojistné 13,5 % z 22 400 = 3 024 Kč přesně.',
    },
    exemptionCategoriesCs: [
      'Držitel průkazu ZTP nebo ZTP/P.',
      'Osoba, která dosáhla důchodového věku, avšak nevznikl jí nárok na starobní důchod.',
      'Osoba, která je současně osobou samostatně výdělečně činnou a odvádí zálohy alespoň z minimálního vyměřovacího základu OSVČ.',
      'Osoba, za kterou je plátcem pojistného stát (§ 3c) — sem od roku 2026 spadá i rodič osobně a řádně pečující alespoň o jedno dítě do 7 let.',
      'Osoba, které jsou poskytovány pouze odměny pěstouna.',
    ],
    employerBearsTopUpOnEmployerObstacle: {
      value: true,
      sourceId: S.healthAct,
      legalBasis: '§ 3 odst. 10 zákona č. 592/1992 Sb.',
      status: 'confirmed-official',
      note: 'Vzniká-li rozdíl z důvodů překážek na straně organizace, hradí doplatek zaměstnavatel. Jde o právní kvalifikaci nepřítomnosti, kterou kalkulačka nemůže odvodit z čísel — je to vstup, který uživatel potvrzuje. Poznámka pod čarou vyhlášky stále odkazuje na zrušený zákoník práce z roku 1965 a žádný orgán aktualizovaný odkaz nepublikoval.',
    },
    topUpRatePercent: {
      value: 13.5,
      sourceId: S.healthAct,
      legalBasis: '§ 3 odst. 10 zákona č. 592/1992 Sb.',
      status: 'confirmed-official',
      note: 'Doplatek se počítá z rozdílu mezi minimálním a skutečným vyměřovacím základem a ve výchozím případě jej hradí ZAMĚSTNANEC SÁM — nedělí se na třetiny. VZP: „(hradí pouze zaměstnanec)".',
    },
    note: 'Výjimky podle § 3 odst. 8 musí trvat po CELÉ rozhodné období. Poměrné snížení podle § 3 odst. 9 se počítá podle kalendářních dnů a dopadá jen na výjimky písm. a) a b). Neplacené volno není od 1. 1. 2015 důvodem pro poměrné snížení.',
  },

  // ── Income tax ───────────────────────────────────────────────────────────
  taxLowerRate: {
    value: 15,
    sourceId: S.taxAct,
    legalBasis: '§ 38h odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: 'Do trojnásobku průměrné mzdy měsíčně.',
  },
  taxUpperRate: {
    value: 23,
    sourceId: S.taxAct,
    legalBasis: '§ 38h odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: 'Z části základu nad trojnásobkem průměrné mzdy.',
  },
  taxUpperMonthlyThreshold: {
    value: 146_901,
    sourceId: S.fs,
    legalBasis: '§ 38h odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: '3 × 48 967 = 146 901 Kč. Roční protějšek je 36 × 48 967 = 1 762 812 Kč.',
  },
  withholdingTaxRate: {
    value: 15,
    sourceId: S.taxAct,
    legalBasis: '§ 36 odst. 2 písm. m) zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: 'Srážková daň se uplatní i v pracovním poměru, pokud zaměstnanec nepodepsal prohlášení A měsíční příjem nedosahuje rozhodné částky 4 500 Kč. Základ i daň se zaokrouhlují DOLŮ (§ 36 odst. 3).',
  },
  basicTaxpayerCreditMonthly: {
    value: 2_570,
    sourceId: S.credits,
    legalBasis: '§ 35ba odst. 1 písm. a), § 35d odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: '30 840 Kč ročně, jedna dvanáctina měsíčně. Měsíčně pouze při podepsaném prohlášení poplatníka.',
  },
  disabilityFirstSecondCreditMonthly: {
    value: 210,
    sourceId: S.credits,
    legalBasis: '§ 35ba odst. 1 písm. c), § 35d odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: '2 520 Kč ročně. Podmínky musí být splněny na počátku kalendářního měsíce (§ 35ba odst. 3).',
  },
  disabilityThirdCreditMonthly: {
    value: 420,
    sourceId: S.credits,
    legalBasis: '§ 35ba odst. 1 písm. d), § 35d odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: '5 040 Kč ročně.',
  },
  ztppCreditMonthly: {
    value: 1_345,
    sourceId: S.credits,
    legalBasis: '§ 35ba odst. 1 písm. e), § 35d odst. 2 zákona č. 586/1992 Sb.',
    status: 'confirmed-official',
    note: '16 140 Kč ročně.',
  },
  childBenefit: {
    firstMonthly: {
      value: 1_267,
      sourceId: S.credits,
      legalBasis: '§ 35c odst. 1, § 35d odst. 2 zákona č. 586/1992 Sb.',
      status: 'confirmed-official',
      note: '15 204 Kč ročně.',
    },
    secondMonthly: {
      value: 1_860,
      sourceId: S.credits,
      legalBasis: '§ 35c odst. 1, § 35d odst. 2 zákona č. 586/1992 Sb.',
      status: 'confirmed-official',
      note: '22 320 Kč ročně.',
    },
    thirdPlusMonthly: {
      value: 2_320,
      sourceId: S.credits,
      legalBasis: '§ 35c odst. 1, § 35d odst. 2 zákona č. 586/1992 Sb.',
      status: 'confirmed-official',
      note: '27 840 Kč ročně.',
    },
    ztppMultiplier: {
      value: 2,
      sourceId: S.credits,
      legalBasis: '§ 35c odst. 7 zákona č. 586/1992 Sb.',
      status: 'confirmed-official',
      note: 'Dítě s průkazem ZTP/P — dvojnásobek příslušné částky.',
    },
    bonusMinMonthlyIncome: {
      value: 11_200,
      sourceId: S.taxAct,
      legalBasis: '§ 35d odst. 4 zákona č. 586/1992 Sb.',
      status: 'derived-from-official',
      note: 'Polovina minimální mzdy 22 400 Kč, zaokrouhlená dolů na celé koruny. Do příjmů se nezahrnují příjmy osvobozené a příjmy zdaněné srážkou.',
    },
    bonusMinPayout: {
      value: 50,
      sourceId: S.taxAct,
      legalBasis: '§ 35d odst. 4 zákona č. 586/1992 Sb.',
      status: 'confirmed-official',
      note: '„Měsíční daňový bonus lze vyplatit, pokud jeho výše činí alespoň 50 Kč." Horní hranice bonusu neexistuje.',
    },
  },

  // ── Statutory employer liability insurance ───────────────────────────────
  liabilityInsurance: {
    status: 'confirmed-official',
    sourceId: S.liabilityDecree,
    legalBasis: '§ 12 a příloha č. 2 vyhlášky č. 125/1993 Sb.',
    // WHY THIS IS A LIST OF RATES AND NOT A LIST OF ACTIVITIES.
    //
    // An earlier version of this table mapped named activities to bands —
    // "Stavebnictví, lesnictví, slévárenství, protipožární ochrana → 9,8 ‰" and
    // so on. Independent review found that grouping wrong, and the attempt to
    // correct it found the sources disagreeing with each other: MPSV's own
    // rendering of příloha č. 2 places OKEČ 02 (lesnictví) at 8,4 ‰ and
    // OKEČ 45 (stavebnictví), 27.5 and 75.25 at 10,5 ‰, while other renderings
    // group them differently again. The annex itself could not be retrieved
    // verbatim: zakonyprolidi returns 403 to a fetcher and MPSV's PDF carries
    // the table as embedded-font glyphs.
    //
    // A wrong band is not a cosmetic error. It multiplies the whole payroll:
    // 9,8 ‰ instead of 8,4 ‰ is 16,7 % too much, every month, per head. So
    // rather than ship a mapping that cannot be evidenced row by row, this
    // offers the eight STATUTORY RATES and names an activity only where the
    // band's own wording is verbatim-verifiable. Everything else is the
    // employer's own determination — which is where the decree puts it anyway:
    // § 12 odst. 2 keys the rate to the employer's "převažující základní
    // činnost", and their insurer's invoice already states the result.
    //
    // The classification is OKEČ, retired by ČSÚ in 2008 and never replaced in
    // the decree. Kooperativa publishes a CZ-NACE converter as an
    // administrative aid, but seven CZ-NACE codes in it resolve to two
    // different rates — up to a 1,9× spread — so it cannot be a lookup either.
    activities: [
      {
        key: 'rate_2_8',
        labelCs: '2,8 ‰ — nejnižší sazbová skupina',
        labelEn: '2.8 ‰ — the lowest rate band',
        labelDe: '2,8 ‰ — niedrigste Satzgruppe',
        ratePerMille: 2.8,
        classificationCode: 'příloha č. 2, sazbová skupina 2,8 ‰',
      },
      {
        key: 'rate_4_2',
        labelCs: '4,2 ‰',
        labelEn: '4.2 ‰',
        labelDe: '4,2 ‰',
        ratePerMille: 4.2,
        classificationCode: 'příloha č. 2, sazbová skupina 4,2 ‰',
      },
      {
        key: 'other_economic',
        labelCs: '5,6 ‰ — Ostatní ekonomické činnosti (zbytková skupina)',
        labelEn: '5.6 ‰ — Other economic activities (the catch-all band)',
        labelDe: '5,6 ‰ — Sonstige wirtschaftliche Tätigkeiten (Auffanggruppe)',
        ratePerMille: 5.6,
        classificationCode: 'příloha č. 2, „Ostatní ekonomické činnosti“',
      },
      {
        key: 'agriculture',
        labelCs: '7 ‰ — Zemědělství',
        labelEn: '7 ‰ — Agriculture',
        labelDe: '7 ‰ — Landwirtschaft',
        ratePerMille: 7,
        classificationCode: 'příloha č. 2, OKEČ 01',
      },
      {
        key: 'rate_8_4',
        labelCs: '8,4 ‰ — mj. lesnictví a těžba dřeva',
        labelEn: '8.4 ‰ — includes forestry and logging',
        labelDe: '8,4 ‰ — u. a. Forstwirtschaft und Holzeinschlag',
        ratePerMille: 8.4,
        classificationCode: 'příloha č. 2, sazbová skupina 8,4 ‰ (mj. OKEČ 02)',
      },
      {
        key: 'rate_9_8',
        labelCs: '9,8 ‰',
        labelEn: '9.8 ‰',
        labelDe: '9,8 ‰',
        ratePerMille: 9.8,
        classificationCode: 'příloha č. 2, sazbová skupina 9,8 ‰',
      },
      {
        // The decree's own qualification, quoted rather than paraphrased. It is
        // NOT an unqualified residual — it excludes "Ostatní ekonomické
        // činnosti" (the real catch-all at 5,6 ‰) and is characterised by
        // hazardous work. Presenting it as "activities not classified elsewhere"
        // invited an employer who belongs at 5,6 ‰ to pick a rate 1,875× higher.
        key: 'hazardous_unclassified',
        labelCs:
          '10,5 ‰ — činnosti nezařazené do jiných skupin (mimo „Ostatní ekonomické činnosti“), zejména práce s výbušninami, radioaktivními látkami, radonem, infekčním materiálem, jedy, ve velkých výškách nebo hloubkách',
        labelEn:
          '10.5 ‰ — activities not classified in another band (excluding “Other economic activities”), chiefly work with explosives, radioactive materials, radon, infectious material, poisons, or at great heights or depths',
        labelDe:
          '10,5 ‰ — nicht in eine andere Gruppe eingeordnete Tätigkeiten (außer „Sonstige wirtschaftliche Tätigkeiten“), vor allem Arbeiten mit Sprengstoffen, radioaktiven Stoffen, Radon, infektiösem Material, Giften oder in großen Höhen oder Tiefen',
        ratePerMille: 10.5,
        classificationCode: 'příloha č. 2, sazbová skupina 10,5 ‰',
      },
      {
        key: 'mining',
        labelCs: '50,4 ‰ — těžba uhlí, uranových a kovových rud (nejvyšší sazba)',
        labelEn: '50.4 ‰ — mining of coal, uranium and metal ores (the highest rate)',
        labelDe: '50,4 ‰ — Kohle-, Uran- und Metallerzbergbau (höchster Satz)',
        ratePerMille: 50.4,
        classificationCode: 'příloha č. 2, sazbová skupina 50,4 ‰',
      },
    ],
    minimumQuarterlyPremium: {
      value: 100,
      sourceId: S.liabilityDecree,
      legalBasis: 'příloha č. 2 vyhlášky č. 125/1993 Sb.',
      status: 'confirmed-official',
      note: '„Minimální pojistné za kalendářní čtvrtletí je 100 Kč." Jde o minimum ZA ZAMĚSTNAVATELE za celé čtvrtletí, nikoli za zaměstnance — na jednotlivého zaměstnance se neaplikuje.',
    },
    annualSocialMaximumApplies: {
      value: false,
      sourceId: S.koop,
      legalBasis: 'metodika správců pojištění; vyhláška č. 125/1993 Sb. mlčí',
      status: 'derived-from-official',
      note: 'Oba správci publikují, že maximální vyměřovací základ podle § 15a zákona č. 589/1992 Sb. se na toto pojištění nevztahuje. Žádný předpis to však nestanoví a doslovné čtení vyhlášky by strop spíše připouštělo. Nejslabší operativní pravidlo v celém tématu — engine se řídí metodikou správců a v poznámce to říká.',
    },
    note: 'Režim je pro rok 2026 v platnosti a nezměněn. Zákon č. 266/2006 Sb. o úrazovém pojištění zaměstnanců byl zrušen zákonem č. 205/2015 Sb. dříve, než nabyl účinnosti. Sazebník stojí ve znění z roku 2002 a lze jej změnit už jen novelou zákoníku práce. Vyhláška neobsahuje žádné pravidlo zaokrouhlování.',
  },

  // ── Reference figures ────────────────────────────────────────────────────
  averageWageMonthly: {
    value: 48_967,
    sourceId: S.socialOverview,
    legalBasis: '§ 23b odst. 4 zákona č. 589/1992 Sb.; nařízení vlády č. 365/2025 Sb.',
    status: 'confirmed-official',
    note: 'Všeobecný vyměřovací základ za rok 2024 46 278 Kč × přepočítací koeficient 1,0581 = 48 966,7518 → nahoru = 48 967 Kč. NEZAMĚŇOVAT s predikcí MF 51 497 Kč, která slouží jen k výpočtu minimální mzdy.',
  },
  minimumWageMonthly: {
    value: 22_400,
    sourceId: S.minimumWage,
    legalBasis: '§ 111 zákona č. 262/2006 Sb.; sdělení MPSV č. 356/2025 Sb.',
    status: 'confirmed-official',
    note: 'Při stanovené týdenní pracovní době 40 hodin. Zaručená mzda je v soukromém sektoru od roku 2025 zrušena — pro zaměstnance odměňovaného mzdou je jedinou dolní hranicí minimální mzda.',
  },
  minimumWageHourly: {
    value: 134.4,
    sourceId: S.minimumWage,
    legalBasis: '§ 111 odst. 4 zákona č. 262/2006 Sb.; sdělení MPSV č. 356/2025 Sb.',
    status: 'confirmed-official',
    note: 'Při 40hodinovém týdnu. Při kratší stanovené týdenní pracovní době se hodinová sazba úměrně zvyšuje (MMx = 134,40 × 40/x) a § 111 odst. 5 pro tento krok NESTANOVÍ žádné zaokrouhlení; hodnoty 143,40 nebo 138,88 Kč, které kolují, nepublikuje žádný oficiální zdroj.',
  },

  rounding: {
    socialAssessmentBase: 'up_to_czk',
    socialPremium: 'up_to_czk',
    healthPremium: 'up_to_czk',
    taxBaseLow: 'up_to_czk',
    taxBaseHigh: 'up_to_hundred_czk',
    taxAdvance: 'up_to_czk',
    withholdingTax: 'down_to_czk',
  },
};

export default CZ_2026;
