import LocalePage from '../../components/locale/LocalePage'
import { PTBR_CONTENT } from '../../lib/locale/content/pt-BR'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function BrazilConsularRoutePtBRPage() {
  return <LocalePage conceptId="brazil-consular-route" locale="pt-BR" content={PTBR_CONTENT['brazil-consular-route']['pt-BR']!} />
}
