import LocalePage from '../../components/locale/LocalePage'
import { DE_CONTENT } from '../../lib/locale/content/de'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function ChoosingAnAgencyDePage() {
  return <LocalePage conceptId="choosing-an-agency" locale="de" content={DE_CONTENT['choosing-an-agency'].de!} />
}
