import LocalePage from '../../components/locale/LocalePage'
import { ES_CONTENT } from '../../lib/locale/content/es'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function TechnicalProfessionsEsPage() {
  return <LocalePage conceptId="technical-professions" locale="es" content={ES_CONTENT['technical-professions'].es!} />
}
