import LocalePage from '../../components/locale/LocalePage'
import { ES_CONTENT } from '../../lib/locale/content/es'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function CandidateDataNoticeEsPage() {
  return <LocalePage conceptId="candidate-data-notice" locale="es" content={ES_CONTENT['candidate-data-notice'].es!} />
}
