import LocalePage from '../../components/locale/LocalePage'
import { EN_CONTENT } from '../../lib/locale/content/en'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function EmployerFaqEnPage() {
  return <LocalePage conceptId="employer-faq" locale="en" content={EN_CONTENT['employer-faq'].en!} />
}
