import LocalePage from '../../components/locale/LocalePage'
import { EN_CONTENT } from '../../lib/locale/content/en'

// Generated by scripts/generate-locale-pages.mjs — do not edit by hand.
// Route identity, canonical, hreflang and content all resolve through the
// locale registry; this wrapper exists so the route is statically enumerable.
export default function HardToFillRolesEnPage() {
  return <LocalePage conceptId="hard-to-fill-roles" locale="en" content={EN_CONTENT['hard-to-fill-roles'].en!} />
}
